language: python
python:
  - 3.8
services:
  - redis-server
  - mongodb
install:
  - pip install -r requirements.txt
script:
  - pylint lib/
  - pylint config/
  - pylint server.py
  - pylint view_config.py
