""" Project constants """


DECORATOR = '========================================================'
DATABASE_CALL_COUNT = 'DATABASE_CALL_COUNT'
REDIS_CALL_COUNT = 'REDIS_CALL_COUNT'
REDIS_UPDATE_TTL_CALL_COUNT = 'REDIS_UPDATE_TTL_CALL_COUNT'

PROTECTED_KEYS = (
    DATABASE_CALL_COUNT,
    REDIS_CALL_COUNT,
    REDIS_UPDATE_TTL_CALL_COUNT)
